# Use an official Nginx image as a parent image
FROM nginx:alpine

# Copy all necessary files to the container
COPY index.html search.html image.html script.js /usr/share/nginx/html/

# Expose port 80 to the outside world
EXPOSE 80
